# -*- coding: utf-8 -*-
"""DECI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0SRzLu52RHiRRUPixZPPoBvuKXJ6rCA
"""
print("hiiiiiiii")
print("Hello from Colab!")

print("new hello")

print("hello2")

print("hello")
print(f"hello plus :, {1+1}")

for i in range(1, 21):
    pattern = '*' * (i if i <= 10 else 21 - i)
    print(f"Line {i:02d}: {pattern} Generating something fun! {pattern}")

import matplotlib.pyplot as plt
import numpy as np

# Set simulation parameters
num_steps = 100
num_walks = 5
plt.figure(figsize=(10, 6))

for i in range(num_walks):
    # Generate random steps: -1 or 1
    steps = np.random.choice([-1, 1], size=num_steps)
    # Compute the cumulative sum to get the walk path
    path = np.cumsum(steps)
    # Prepend a starting point at 0
    path = np.insert(path, 0, 0)
    plt.plot(path, label=f'Walk {i+1}')

plt.title("20-Line Random Walk Simulation")
plt.xlabel("Steps")
plt.ylabel("Position")
plt.legend()
plt.grid(True)
plt.show()

