print("hi there")


# -*- coding: utf-8 -*-
"""week16 activity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BudkzKUsHdULZTCbpLDYgO2D6Alxdh0
"""

import pandas as pd
import requests
HEADERS = {
    "user-agent": "AI and computer science student/1.0 (student)"
}

page = requests.get("https://books.toscrape.com/index.html",
headers=HEADERS
)

print("request code statues : ", page.status_code)

from bs4 import BeautifulSoup
soup = BeautifulSoup(page.text, "html.parser")
book_cards = soup.find_all("article", class_="product_pod")
print("the number of books found", len(book_cards))

RATING_WORDS = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
scraped_records = []
for card in book_cards[:6]:
  title = card.h3.a["title"]
  price_gbp_str = card.find("p", class_="price_color").text.strip()
  price_gbp = float(price_gbp_str.replace('Â£', ''))

  # Correctly find the rating element using the class 'star-rating'
  rating_word = card.find("p", class_="star-rating")["class"][1]
  rating = RATING_WORDS.get(rating_word)
  scraped_records.append(
      (title, price_gbp, rating_word)
  )
  print("title\n", title, "price\n", price_gbp, "rating\n", rating_word)

scraped_df = pd.DataFrame(scraped_records)
scraped_df.columns = ['title', 'price_gbp', 'rating_word']
scraped_df

sample_title = scraped_df["title"].iloc[0]
response = requests.get("https://openlibrary.org/search.json", params={"title": sample_title, "limit": 1})
print("status code : ", response.status_code)
response.json()

import time
api_records = []
for title in scraped_df["title"]:
  response = requests.get("https://openlibrary.org/search.json", params={"title": title})
  response_json = response.json()
  print("status code : ", response.status_code)

  author_name = None
  first_publish_year = None

  if response_json and 'docs' in response_json and len(response_json['docs']) > 0:
    doc = response_json['docs'][0] # Take the first document
    if 'author_name' in doc and len(doc['author_name']) > 0:
      author_name = doc['author_name'][0] # Get the first author's name
    if 'first_publish_year' in doc:
      first_publish_year = doc['first_publish_year']

  api_records.append({
      'title': title,
      'author': author_name,
      'first_publish_year': first_publish_year
  })
  # Removed break to process all titles and added a small delay
  time.sleep(0.3)

# Print details for the first record in api_records, if available
if api_records:
  first_record = api_records[0]
  print(f"Author: {first_record['author']}, Publish Year: {first_record['first_publish_year']}")
else:
  print("No API records found.")

api_df = pd.DataFrame(api_records)
api_df

scraped_df.columns = ['title', 'price_gbp', 'rating_word']
combined_df = pd.merge(scraped_df, api_df, on="title", how="left")
combined_df

combined_df.to_csv("book_fair_collected.csv", index=False)

reloaded_df = pd.read_csv("book_fair_collected.csv")
reloaded_df.head()

reloaded_df.info()

reloaded_df.describe()

reloaded_df.shape

reloaded_df.isna().sum()
